//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 09.02.2016 16:32:42
namespace OData1c_console.TestBase
{
    
    /// <summary>
    /// There are no comments for EnterpriseV8 in the schema.
    /// </summary>
    public partial class EnterpriseV8 : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new EnterpriseV8 object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public EnterpriseV8(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "StandardODATA", "OData1c_console.OData1c");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("OData1c_console.OData1c", global::System.StringComparison.Ordinal))
            {
                return string.Concat("StandardODATA.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for Document_АктВыполненныхРабот in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Document_АктВыполненныхРабот> Document_АктВыполненныхРабот
        {
            get
            {
                if ((this._Document_АктВыполненныхРабот == null))
                {
                    this._Document_АктВыполненныхРабот = base.CreateQuery<Document_АктВыполненныхРабот>("Document_АктВыполненныхРабот");
                }
                return this._Document_АктВыполненныхРабот;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Document_АктВыполненныхРабот> _Document_АктВыполненныхРабот;
        /// <summary>
        /// There are no comments for Document_АктВыполненныхРабот_Работы in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Document_АктВыполненныхРабот_Работы> Document_АктВыполненныхРабот_Работы
        {
            get
            {
                if ((this._Document_АктВыполненныхРабот_Работы == null))
                {
                    this._Document_АктВыполненныхРабот_Работы = base.CreateQuery<Document_АктВыполненныхРабот_Работы>("Document_АктВыполненныхРабот_Работы");
                }
                return this._Document_АктВыполненныхРабот_Работы;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Document_АктВыполненныхРабот_Работы> _Document_АктВыполненныхРабот_Работы;
        /// <summary>
        /// There are no comments for Catalog_Контрагенты in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Catalog_Контрагенты> Catalog_Контрагенты
        {
            get
            {
                if ((this._Catalog_Контрагенты == null))
                {
                    this._Catalog_Контрагенты = base.CreateQuery<Catalog_Контрагенты>("Catalog_Контрагенты");
                }
                return this._Catalog_Контрагенты;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Catalog_Контрагенты> _Catalog_Контрагенты;
        /// <summary>
        /// There are no comments for Document_АктВыполненныхРабот in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToDocument_АктВыполненныхРабот(Document_АктВыполненныхРабот document_АктВыполненныхРабот)
        {
            base.AddObject("Document_АктВыполненныхРабот", document_АктВыполненныхРабот);
        }
        /// <summary>
        /// There are no comments for Document_АктВыполненныхРабот_Работы in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToDocument_АктВыполненныхРабот_Работы(Document_АктВыполненныхРабот_Работы document_АктВыполненныхРабот_Работы)
        {
            base.AddObject("Document_АктВыполненныхРабот_Работы", document_АктВыполненныхРабот_Работы);
        }
        /// <summary>
        /// There are no comments for Catalog_Контрагенты in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToCatalog_Контрагенты(Catalog_Контрагенты catalog_Контрагенты)
        {
            base.AddObject("Catalog_Контрагенты", catalog_Контрагенты);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart0 = "<edmx:Edmx xmlns:edmx=\"http://schemas.microsoft.com/ado/2007/06/edmx\" Version=\"1." +
                "0\"><edmx:DataServices xmlns:m=\"http://schemas.microsoft.com/ado/2007/08/dataserv" +
                "ices/metadata\" m:DataServiceVersion=\"3.0\" m:MaxDataServiceVersion=\"3.0\"><Schema " +
                "xmlns=\"http://schemas.microsoft.com/ado/2009/11/edm\" Namespace=\"StandardODATA\"><" +
                "EntityType Name=\"Document_АктВыполненныхРабот\"><Key><PropertyRef Name=\"Ref_Key\" " +
                "/></Key><Property Name=\"Ref_Key\" Type=\"Edm.Guid\" Nullable=\"false\" /><Property Na" +
                "me=\"DataVersion\" Type=\"Edm.String\" Nullable=\"true\" /><Property Name=\"Number\" Typ" +
                "e=\"Edm.String\" Nullable=\"true\" /><Property Name=\"Date\" Type=\"Edm.DateTime\" Nulla" +
                "ble=\"true\" /><Property Name=\"DeletionMark\" Type=\"Edm.Boolean\" Nullable=\"true\" />" +
                "<Property Name=\"Posted\" Type=\"Edm.Boolean\" Nullable=\"true\" /><Property Name=\"Кон" +
                "трагент_Key\" Type=\"Edm.Guid\" Nullable=\"true\" /><Property Name=\"Работы\" Type=\"Col" +
                "lection(StandardODATA.Document_АктВыполненныхРабот_Работы_RowType)\" Nullable=\"tr" +
                "ue\" /><NavigationProperty Name=\"Контрагент\" Relationship=\"StandardODATA.Document" +
                "_АктВыполненныхРабот_Контрагент\" FromRole=\"Begin\" ToRole=\"End\" /></EntityType><E" +
                "ntityType Name=\"Document_АктВыполненныхРабот_Работы\"><Key><PropertyRef Name=\"Ref" +
                "_Key\" /><PropertyRef Name=\"LineNumber\" /></Key><Property Name=\"Ref_Key\" Type=\"Ed" +
                "m.Guid\" Nullable=\"false\" /><Property Name=\"LineNumber\" Type=\"Edm.Int64\" Nullable" +
                "=\"false\" /><Property Name=\"Сумма\" Type=\"Edm.Double\" Nullable=\"true\" /><Property " +
                "Name=\"Описание\" Type=\"Edm.String\" Nullable=\"true\" /></EntityType><EntityType Nam" +
                "e=\"Catalog_Контрагенты\"><Key><PropertyRef Name=\"Ref_Key\" /></Key><Property Name=" +
                "\"Ref_Key\" Type=\"Edm.Guid\" Nullable=\"false\" /><Property Name=\"DataVersion\" Type=\"" +
                "Edm.String\" Nullable=\"true\" /><Property Name=\"Description\" Type=\"Edm.String\" Nul" +
                "lable=\"true\" /><Property Name=\"Code\" Type=\"Edm.String\" Nullable=\"true\" /><Proper" +
                "ty Name=\"DeletionMark\" Type=\"Edm.Boolean\" Nullable=\"true\" /><Property Name=\"Вид\"" +
                " Type=\"Edm.String\" Nullable=\"true\" /></EntityType><ComplexType Name=\"NumberQuali" +
                "fiers\"><Property Name=\"AllowedSign\" Type=\"Edm.String\" Nullable=\"false\" /><Proper" +
                "ty Name=\"Digits\" Type=\"Edm.Int16\" Nullable=\"false\" /><Property Name=\"FractionDig" +
                "its\" Type=\"Edm.Int16\" Nullable=\"false\" /></ComplexType><ComplexType Name=\"TypeDe" +
                "scription\"><Property Name=\"Types\" Type=\"Collection(Edm.String)\" Nullable=\"false\"" +
                " /><Property Name=\"NumberQualifiers\" Type=\"StandardODATA.NumberQualifiers\" Nulla" +
                "ble=\"false\" /></ComplexType><ComplexType Name=\"PointInTime\"><Property Name=\"Ref\"" +
                " Type=\"Edm.String\" Nullable=\"false\" /><Property Name=\"Date\" Type=\"Edm.DateTime\" " +
                "Nullable=\"false\" /></ComplexType><ComplexType Name=\"Document_АктВыполненныхРабот" +
                "_Работы_RowType\"><Property Name=\"Ref_Key\" Type=\"Edm.Guid\" Nullable=\"false\" /><Pr" +
                "operty Name=\"LineNumber\" Type=\"Edm.Int64\" Nullable=\"false\" /><Property Name=\"Сум" +
                "ма\" Type=\"Edm.Double\" Nullable=\"true\" /><Property Name=\"Описание\" Type=\"Edm.Stri" +
                "ng\" Nullable=\"true\" /></ComplexType><Association Name=\"Document_АктВыполненныхРа" +
                "бот_Контрагент\"><End Role=\"Begin\" Type=\"StandardODATA.Document_АктВыполненныхРаб" +
                "от\" Multiplicity=\"*\" /><End Role=\"End\" Type=\"StandardODATA.Catalog_Контрагенты\" " +
                "Multiplicity=\"0..1\" /></Association><EnumType Name=\"ТипКонтрагента\" UnderlyingTy" +
                "pe=\"Edm.Int32\"><Member Name=\"ФизЛицо\" /><Member Name=\"ЮрЛицо\" /></EnumType><Enum" +
                "Type Name=\"AccountType\" UnderlyingType=\"Edm.Int32\"><Member Name=\"Active\" /><Memb" +
                "er Name=\"ActivePassive\" /><Member Name=\"Passive\" /></EnumType><EnumType Name=\"Ac" +
                "countingRecordType\" UnderlyingType=\"Edm.Int32\"><Member Name=\"Credit\" /><Member N" +
                "ame=\"Debit\" /></EnumType><EnumType Name=\"AllowedSign\" UnderlyingType=\"Edm.Int32\"" +
                "><Member Name=\"Any\" /><Member Name=\"Nonnegative\" /></EnumType><EntityContainer N" +
                "ame=\"EnterpriseV8\" m:IsDefaultEntityContainer=\"true\"><EntitySet Name=\"Document_А" +
                "ктВыполненныхРабот\" EntityType=\"StandardODATA.Document_АктВыполненныхРабот\" /><E" +
                "ntitySet Name=\"Document_АктВыполненныхРабот_Работы\" EntityType=\"StandardODATA.Do" +
                "cument_АктВыполненныхРабот_Работы\" /><EntitySet Name=\"Catalog_Контрагенты\" Entit" +
                "yType=\"StandardODATA.Catalog_Контрагенты\" /><FunctionImport Name=\"Post\" IsBindab" +
                "le=\"true\" IsSideEffecting=\"true\"><Parameter Name=\"bindingParameter\" Type=\"Standa" +
                "rdODATA.Document_АктВыполненныхРабот\" /><Parameter Name=\"PostingModeOperational\"" +
                " Type=\"Edm.Boolean\" /></FunctionImport><FunctionImport Name=\"Unpost\" IsBindable=" +
                "\"true\" IsSideEffecting=\"true\"><Parameter Name=\"bindingParameter\" Type=\"StandardO" +
                "DATA.Document_АктВыполненныхРабот\" /><Parameter Name=\"PostingModeOperational\" Ty" +
                "pe=\"Edm.Boolean\" /></FunctionImport></EntityContainer></Schema></edmx:DataServic" +
                "es></edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static string GetConcatenatedEdmxString()
            {
                return string.Concat(ModelPart0);
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            public static global::Microsoft.Data.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel LoadModelFromString()
            {
                string edmxToParse = GetConcatenatedEdmxString();
                global::System.Xml.XmlReader reader = CreateXmlReader(edmxToParse);
                try
                {
                    return global::Microsoft.Data.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
    /// <summary>
    /// There are no comments for ComplexType StandardODATA.Document_АктВыполненныхРабот_Работы_RowType in the schema.
    /// </summary>
    public partial class Document_АктВыполненныхРабот_Работы_RowType : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Document_АктВыполненныхРабот_Работы_RowType object.
        /// </summary>
        /// <param name="ref_Key">Initial value of Ref_Key.</param>
        /// <param name="lineNumber">Initial value of LineNumber.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Document_АктВыполненныхРабот_Работы_RowType CreateDocument_АктВыполненныхРабот_Работы_RowType(global::System.Guid ref_Key, long lineNumber)
        {
            Document_АктВыполненныхРабот_Работы_RowType document_АктВыполненныхРабот_Работы_RowType = new Document_АктВыполненныхРабот_Работы_RowType();
            document_АктВыполненныхРабот_Работы_RowType.Ref_Key = ref_Key;
            document_АктВыполненныхРабот_Работы_RowType.LineNumber = lineNumber;
            return document_АктВыполненныхРабот_Работы_RowType;
        }
        /// <summary>
        /// There are no comments for Property Ref_Key in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid Ref_Key
        {
            get
            {
                return this._Ref_Key;
            }
            set
            {
                this.OnRef_KeyChanging(value);
                this._Ref_Key = value;
                this.OnRef_KeyChanged();
                this.OnPropertyChanged("Ref_Key");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _Ref_Key;
        partial void OnRef_KeyChanging(global::System.Guid value);
        partial void OnRef_KeyChanged();
        /// <summary>
        /// There are no comments for Property LineNumber in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public long LineNumber
        {
            get
            {
                return this._LineNumber;
            }
            set
            {
                this.OnLineNumberChanging(value);
                this._LineNumber = value;
                this.OnLineNumberChanged();
                this.OnPropertyChanged("LineNumber");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private long _LineNumber;
        partial void OnLineNumberChanging(long value);
        partial void OnLineNumberChanged();
        /// <summary>
        /// There are no comments for Property Сумма in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<double> Сумма
        {
            get
            {
                return this._Сумма;
            }
            set
            {
                this.OnСуммаChanging(value);
                this._Сумма = value;
                this.OnСуммаChanged();
                this.OnPropertyChanged("Сумма");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<double> _Сумма;
        partial void OnСуммаChanging(global::System.Nullable<double> value);
        partial void OnСуммаChanged();
        /// <summary>
        /// There are no comments for Property Описание in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Описание
        {
            get
            {
                return this._Описание;
            }
            set
            {
                this.OnОписаниеChanging(value);
                this._Описание = value;
                this.OnОписаниеChanged();
                this.OnPropertyChanged("Описание");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Описание;
        partial void OnОписаниеChanging(string value);
        partial void OnОписаниеChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for StandardODATA.Document_АктВыполненныхРабот in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Ref_Key
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Document_АктВыполненныхРабот")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Ref_Key")]
    public partial class Document_АктВыполненныхРабот : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Document_АктВыполненныхРабот object.
        /// </summary>
        /// <param name="ref_Key">Initial value of Ref_Key.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Document_АктВыполненныхРабот CreateDocument_АктВыполненныхРабот(global::System.Guid ref_Key)
        {
            Document_АктВыполненныхРабот document_АктВыполненныхРабот = new Document_АктВыполненныхРабот();
            document_АктВыполненныхРабот.Ref_Key = ref_Key;
            return document_АктВыполненныхРабот;
        }
        /// <summary>
        /// There are no comments for Property Ref_Key in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid Ref_Key
        {
            get
            {
                return this._Ref_Key;
            }
            set
            {
                this.OnRef_KeyChanging(value);
                this._Ref_Key = value;
                this.OnRef_KeyChanged();
                this.OnPropertyChanged("Ref_Key");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _Ref_Key;
        partial void OnRef_KeyChanging(global::System.Guid value);
        partial void OnRef_KeyChanged();
        /// <summary>
        /// There are no comments for Property DataVersion in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string DataVersion
        {
            get
            {
                return this._DataVersion;
            }
            set
            {
                this.OnDataVersionChanging(value);
                this._DataVersion = value;
                this.OnDataVersionChanged();
                this.OnPropertyChanged("DataVersion");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _DataVersion;
        partial void OnDataVersionChanging(string value);
        partial void OnDataVersionChanged();
        /// <summary>
        /// There are no comments for Property Number in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Number
        {
            get
            {
                return this._Number;
            }
            set
            {
                this.OnNumberChanging(value);
                this._Number = value;
                this.OnNumberChanged();
                this.OnPropertyChanged("Number");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Number;
        partial void OnNumberChanging(string value);
        partial void OnNumberChanged();
        /// <summary>
        /// There are no comments for Property Date in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> Date
        {
            get
            {
                return this._Date;
            }
            set
            {
                this.OnDateChanging(value);
                this._Date = value;
                this.OnDateChanged();
                this.OnPropertyChanged("Date");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _Date;
        partial void OnDateChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnDateChanged();
        /// <summary>
        /// There are no comments for Property DeletionMark in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<bool> DeletionMark
        {
            get
            {
                return this._DeletionMark;
            }
            set
            {
                this.OnDeletionMarkChanging(value);
                this._DeletionMark = value;
                this.OnDeletionMarkChanged();
                this.OnPropertyChanged("DeletionMark");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<bool> _DeletionMark;
        partial void OnDeletionMarkChanging(global::System.Nullable<bool> value);
        partial void OnDeletionMarkChanged();
        /// <summary>
        /// There are no comments for Property Posted in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<bool> Posted
        {
            get
            {
                return this._Posted;
            }
            set
            {
                this.OnPostedChanging(value);
                this._Posted = value;
                this.OnPostedChanged();
                this.OnPropertyChanged("Posted");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<bool> _Posted;
        partial void OnPostedChanging(global::System.Nullable<bool> value);
        partial void OnPostedChanged();
        /// <summary>
        /// There are no comments for Property Контрагент_Key in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.Guid> Контрагент_Key
        {
            get
            {
                return this._Контрагент_Key;
            }
            set
            {
                this.OnКонтрагент_KeyChanging(value);
                this._Контрагент_Key = value;
                this.OnКонтрагент_KeyChanged();
                this.OnPropertyChanged("Контрагент_Key");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.Guid> _Контрагент_Key;
        partial void OnКонтрагент_KeyChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnКонтрагент_KeyChanged();
        /// <summary>
        /// There are no comments for Property Работы in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Collections.ObjectModel.ObservableCollection<Document_АктВыполненныхРабот_Работы_RowType> Работы
        {
            get
            {
                return this._Работы;
            }
            set
            {
                this.OnРаботыChanging(value);
                this._Работы = value;
                this.OnРаботыChanged();
                this.OnPropertyChanged("Работы");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Collections.ObjectModel.ObservableCollection<Document_АктВыполненныхРабот_Работы_RowType> _Работы = new global::System.Collections.ObjectModel.ObservableCollection<Document_АктВыполненныхРабот_Работы_RowType>();
        partial void OnРаботыChanging(global::System.Collections.ObjectModel.ObservableCollection<Document_АктВыполненныхРабот_Работы_RowType> value);
        partial void OnРаботыChanged();
        /// <summary>
        /// There are no comments for Контрагент in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Catalog_Контрагенты Контрагент
        {
            get
            {
                return this._Контрагент;
            }
            set
            {
                this._Контрагент = value;
                this.OnPropertyChanged("Контрагент");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Catalog_Контрагенты _Контрагент;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for StandardODATA.Document_АктВыполненныхРабот_Работы in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Ref_Key
    /// LineNumber
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Document_АктВыполненныхРабот_Работы")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Ref_Key", "LineNumber")]
    public partial class Document_АктВыполненныхРабот_Работы : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Document_АктВыполненныхРабот_Работы object.
        /// </summary>
        /// <param name="ref_Key">Initial value of Ref_Key.</param>
        /// <param name="lineNumber">Initial value of LineNumber.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Document_АктВыполненныхРабот_Работы CreateDocument_АктВыполненныхРабот_Работы(global::System.Guid ref_Key, long lineNumber)
        {
            Document_АктВыполненныхРабот_Работы document_АктВыполненныхРабот_Работы = new Document_АктВыполненныхРабот_Работы();
            document_АктВыполненныхРабот_Работы.Ref_Key = ref_Key;
            document_АктВыполненныхРабот_Работы.LineNumber = lineNumber;
            return document_АктВыполненныхРабот_Работы;
        }
        /// <summary>
        /// There are no comments for Property Ref_Key in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid Ref_Key
        {
            get
            {
                return this._Ref_Key;
            }
            set
            {
                this.OnRef_KeyChanging(value);
                this._Ref_Key = value;
                this.OnRef_KeyChanged();
                this.OnPropertyChanged("Ref_Key");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _Ref_Key;
        partial void OnRef_KeyChanging(global::System.Guid value);
        partial void OnRef_KeyChanged();
        /// <summary>
        /// There are no comments for Property LineNumber in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public long LineNumber
        {
            get
            {
                return this._LineNumber;
            }
            set
            {
                this.OnLineNumberChanging(value);
                this._LineNumber = value;
                this.OnLineNumberChanged();
                this.OnPropertyChanged("LineNumber");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private long _LineNumber;
        partial void OnLineNumberChanging(long value);
        partial void OnLineNumberChanged();
        /// <summary>
        /// There are no comments for Property Сумма in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<double> Сумма
        {
            get
            {
                return this._Сумма;
            }
            set
            {
                this.OnСуммаChanging(value);
                this._Сумма = value;
                this.OnСуммаChanged();
                this.OnPropertyChanged("Сумма");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<double> _Сумма;
        partial void OnСуммаChanging(global::System.Nullable<double> value);
        partial void OnСуммаChanged();
        /// <summary>
        /// There are no comments for Property Описание in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Описание
        {
            get
            {
                return this._Описание;
            }
            set
            {
                this.OnОписаниеChanging(value);
                this._Описание = value;
                this.OnОписаниеChanged();
                this.OnPropertyChanged("Описание");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Описание;
        partial void OnОписаниеChanging(string value);
        partial void OnОписаниеChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for StandardODATA.Catalog_Контрагенты in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Ref_Key
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Catalog_Контрагенты")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Ref_Key")]
    public partial class Catalog_Контрагенты : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Catalog_Контрагенты object.
        /// </summary>
        /// <param name="ref_Key">Initial value of Ref_Key.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Catalog_Контрагенты CreateCatalog_Контрагенты(global::System.Guid ref_Key)
        {
            Catalog_Контрагенты catalog_Контрагенты = new Catalog_Контрагенты();
            catalog_Контрагенты.Ref_Key = ref_Key;
            return catalog_Контрагенты;
        }
        /// <summary>
        /// There are no comments for Property Ref_Key in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid Ref_Key
        {
            get
            {
                return this._Ref_Key;
            }
            set
            {
                this.OnRef_KeyChanging(value);
                this._Ref_Key = value;
                this.OnRef_KeyChanged();
                this.OnPropertyChanged("Ref_Key");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _Ref_Key;
        partial void OnRef_KeyChanging(global::System.Guid value);
        partial void OnRef_KeyChanged();
        /// <summary>
        /// There are no comments for Property DataVersion in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string DataVersion
        {
            get
            {
                return this._DataVersion;
            }
            set
            {
                this.OnDataVersionChanging(value);
                this._DataVersion = value;
                this.OnDataVersionChanged();
                this.OnPropertyChanged("DataVersion");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _DataVersion;
        partial void OnDataVersionChanging(string value);
        partial void OnDataVersionChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
                this.OnPropertyChanged("Description");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property Code in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Code
        {
            get
            {
                return this._Code;
            }
            set
            {
                this.OnCodeChanging(value);
                this._Code = value;
                this.OnCodeChanged();
                this.OnPropertyChanged("Code");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Code;
        partial void OnCodeChanging(string value);
        partial void OnCodeChanged();
        /// <summary>
        /// There are no comments for Property DeletionMark in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<bool> DeletionMark
        {
            get
            {
                return this._DeletionMark;
            }
            set
            {
                this.OnDeletionMarkChanging(value);
                this._DeletionMark = value;
                this.OnDeletionMarkChanged();
                this.OnPropertyChanged("DeletionMark");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<bool> _DeletionMark;
        partial void OnDeletionMarkChanging(global::System.Nullable<bool> value);
        partial void OnDeletionMarkChanged();
        /// <summary>
        /// There are no comments for Property Вид in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Вид
        {
            get
            {
                return this._Вид;
            }
            set
            {
                this.OnВидChanging(value);
                this._Вид = value;
                this.OnВидChanged();
                this.OnPropertyChanged("Вид");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Вид;
        partial void OnВидChanging(string value);
        partial void OnВидChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for ComplexType StandardODATA.NumberQualifiers in the schema.
    /// </summary>
    public partial class NumberQualifiers : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new NumberQualifiers object.
        /// </summary>
        /// <param name="allowedSign">Initial value of AllowedSign.</param>
        /// <param name="digits">Initial value of Digits.</param>
        /// <param name="fractionDigits">Initial value of FractionDigits.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static NumberQualifiers CreateNumberQualifiers(string allowedSign, short digits, short fractionDigits)
        {
            NumberQualifiers numberQualifiers = new NumberQualifiers();
            numberQualifiers.AllowedSign = allowedSign;
            numberQualifiers.Digits = digits;
            numberQualifiers.FractionDigits = fractionDigits;
            return numberQualifiers;
        }
        /// <summary>
        /// There are no comments for Property AllowedSign in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string AllowedSign
        {
            get
            {
                return this._AllowedSign;
            }
            set
            {
                this.OnAllowedSignChanging(value);
                this._AllowedSign = value;
                this.OnAllowedSignChanged();
                this.OnPropertyChanged("AllowedSign");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _AllowedSign;
        partial void OnAllowedSignChanging(string value);
        partial void OnAllowedSignChanged();
        /// <summary>
        /// There are no comments for Property Digits in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public short Digits
        {
            get
            {
                return this._Digits;
            }
            set
            {
                this.OnDigitsChanging(value);
                this._Digits = value;
                this.OnDigitsChanged();
                this.OnPropertyChanged("Digits");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private short _Digits;
        partial void OnDigitsChanging(short value);
        partial void OnDigitsChanged();
        /// <summary>
        /// There are no comments for Property FractionDigits in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public short FractionDigits
        {
            get
            {
                return this._FractionDigits;
            }
            set
            {
                this.OnFractionDigitsChanging(value);
                this._FractionDigits = value;
                this.OnFractionDigitsChanged();
                this.OnPropertyChanged("FractionDigits");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private short _FractionDigits;
        partial void OnFractionDigitsChanging(short value);
        partial void OnFractionDigitsChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for ComplexType StandardODATA.TypeDescription in the schema.
    /// </summary>
    public partial class TypeDescription : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new TypeDescription object.
        /// </summary>
        /// <param name="types">Initial value of Types.</param>
        /// <param name="numberQualifiers">Initial value of NumberQualifiers.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static TypeDescription CreateTypeDescription(global::System.Collections.ObjectModel.ObservableCollection<string> types, NumberQualifiers numberQualifiers)
        {
            TypeDescription typeDescription = new TypeDescription();
            if ((types == null))
            {
                throw new global::System.ArgumentNullException("types");
            }
            typeDescription.Types = types;
            if ((numberQualifiers == null))
            {
                throw new global::System.ArgumentNullException("numberQualifiers");
            }
            typeDescription.NumberQualifiers = numberQualifiers;
            return typeDescription;
        }
        /// <summary>
        /// There are no comments for Property Types in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Collections.ObjectModel.ObservableCollection<string> Types
        {
            get
            {
                return this._Types;
            }
            set
            {
                this.OnTypesChanging(value);
                this._Types = value;
                this.OnTypesChanged();
                this.OnPropertyChanged("Types");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Collections.ObjectModel.ObservableCollection<string> _Types = new global::System.Collections.ObjectModel.ObservableCollection<string>();
        partial void OnTypesChanging(global::System.Collections.ObjectModel.ObservableCollection<string> value);
        partial void OnTypesChanged();
        /// <summary>
        /// There are no comments for Property NumberQualifiers in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public NumberQualifiers NumberQualifiers
        {
            get
            {
                if (((this._NumberQualifiers == null) 
                            && (this._NumberQualifiersInitialized != true)))
                {
                    this._NumberQualifiers = new NumberQualifiers();
                    this._NumberQualifiersInitialized = true;
                }
                return this._NumberQualifiers;
            }
            set
            {
                this.OnNumberQualifiersChanging(value);
                this._NumberQualifiers = value;
                this._NumberQualifiersInitialized = true;
                this.OnNumberQualifiersChanged();
                this.OnPropertyChanged("NumberQualifiers");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private NumberQualifiers _NumberQualifiers;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _NumberQualifiersInitialized;
        partial void OnNumberQualifiersChanging(NumberQualifiers value);
        partial void OnNumberQualifiersChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for ComplexType StandardODATA.PointInTime in the schema.
    /// </summary>
    public partial class PointInTime : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new PointInTime object.
        /// </summary>
        /// <param name="ref">Initial value of Ref.</param>
        /// <param name="date">Initial value of Date.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static PointInTime CreatePointInTime(string @ref, global::System.DateTime date)
        {
            PointInTime pointInTime = new PointInTime();
            pointInTime.Ref = @ref;
            pointInTime.Date = date;
            return pointInTime;
        }
        /// <summary>
        /// There are no comments for Property Ref in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Ref
        {
            get
            {
                return this._Ref;
            }
            set
            {
                this.OnRefChanging(value);
                this._Ref = value;
                this.OnRefChanged();
                this.OnPropertyChanged("Ref");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Ref;
        partial void OnRefChanging(string value);
        partial void OnRefChanged();
        /// <summary>
        /// There are no comments for Property Date in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime Date
        {
            get
            {
                return this._Date;
            }
            set
            {
                this.OnDateChanging(value);
                this._Date = value;
                this.OnDateChanged();
                this.OnPropertyChanged("Date");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
